service: aws-python-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  
plugins:
  - serverless-offline-sqs
  - serverless-offline
  - serverless-python-requirements

package:
  excludeDevDependencies: true
  individually: true
  patterns:
    - '!node_modules/**'
    - '!.idea/**'
    - '!.mypy_cache/**'
    - '!venv/**'
    - '!__pycache__/**'
    - '!.vscode/**'

custom:
  serverless-offline-sqs:
    autoCreate: false
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: eu-east-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false

  serverless-offline:
    useDocker: false
    port: 3000

  mySqsName: ${self:provider.stage}-my-sqs
  pythonRequirements:
    dockerizePip: non-linux

functions:
  publisher:
    handler: publisher.process
    events:
      - httpApi:
          path: /
          method: get

  consumer:
    handler: consumer.process
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MySQS
              - Arn
          
          
resources:
  Resources:
    MySQS:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.mySqsName}
        VisibilityTimeout: 30
